Added auth_header_value check to avoid an Attribute Error.
Without this check it is possible to get an AttributeError: 'NoneType'
object has no attribute 'split' caused by key =
auth_header_value.split(' ')[1].  In this case the except in the try
statement is not raised.  This prevents that.